### PR TITLE
[WIP] spell check, formatting, code cleanup

### PR DESCRIPTION
**Pull request by sungam3r**
This is the cleanup I did while reviewing the code briefly.

### CODE REVIEW

**Comment by sungam3r** [comment]
@rose-a Could you help me with tests? I see that github actions works only on [my branch](https://github.com/sungam3r/graphql-client/commits/code-cleanup), but not on this PR. Locally tests run without errors. I understand that I’ve made a lot of changes, but I still would like to understand whether the tests fall because of them or not.

**Comment by rose-a** [comment]
Hi, nice to see you investing in this project!

The issue with the tests failing (randomly) on GitHub Actions is the thing which currently bothers me the most, and where I'm running out of ideas why they keep failing. (so it's currently nothing "special" in your case)...

I'm trying to keep track of this in #161 and I'm currently overhauling the observable test helpers in #213 (and planning to propose a PR to FluentAssertions if those tests finally run).

Seems to be a threading issue where the reception of the notification pushed by the observable is blocked by the test waiting for it, which is also somehow dependent on the machine it runs on....

**Comment by sungam3r** [comment]
I will wait for your changes and then resolve conflicts.

**Comment by sungam3r** [comment]
изображение

**Comment by sungam3r** [comment]
> btw. please target develop

There is no develop anymore.

**Comment by sungam3r** [comment]
@rose-a Done. Tests success locally.

**Comment by rose-a** [comment]
> There is no develop anymore.

Correct, moved to "GitHubFlow" to simplify things...

**Pull request merged**
