### PR TITLE
Add the ability to include Headers for Request Message

### PR DESCRIPTION
**Pull request by nothingalike**
This is how i was able to resolve my issues. I needed to add auth tokens into the headers of the request.

### CODE REVIEW

**Comment by sungam3r** [comment]
So it is global (shared) headers for all requests and obviously there may be problems when changing headers in runtime.

**Comment by rose-a** [comment]
Where is the difference to setting the `DefaultRequestHeaders` property of the `HttpClient` used inside `GraphQLHttpClient`?

**Comment by nothingalike** [comment]
From my experience and testing, DefaultRequestHeaders did not add the correct headers to the Http Request.

**Comment by nothingalike** [comment]
@sungam3r  those are probably fair points and open to suggestions, but this update allowed me to execute calls with headers that were needed. More specific: hitting Shopify GraphQL

**Comment by rose-a** [comment]
What exactly did go wrong when you used `DefaultRequestHeaders`? I'd really like to get to the bottom of this, because it's quite hard to believe that this does not work...

**Comment by nothingalike** [comment]
@rose-a so not sure what to tell you other than those are on two different objects. DefaultRequestHeaders are on the actual client itself while the headers im populating go on the RequestMessage themselves. I can rename Header to MessageHeaders. When testing with Fiddler and posting GraphQL messages to Shopify, these were the headers i needed to populate.

**Comment by rose-a** [comment]
> so not sure what to tell you

What exactly does not work when you set the headers you need for the Shopify API using the *DefaultRequestHeaders* property on the *HttpClient* used by *GraphQLHttpClient*?

Maybe show us some code in which the problems manifest themselves?

Citing Microsofts documentation of the *HttpClient.DefaultRequestHeaders Property*:

> The headers which should be sent with each request.

Thats what actually happens and it works for me without any problems (i.e. for sending authentication tokens)!

**Comment by sungam3r** [comment]
My 50 cents - if you look at the source code of HttpClient internals then you will see that `HttpClient.DefaultRequestHeaders` are copied into `HttpRequestMessage.Headers` on each request.

**Comment by nothingalike** [comment]
Interesting ill retry.

**Comment by nothingalike** [comment]
Not sure what i did differently the first time. defaultheaders look good. thank you

**Comment by arisliang** [comment]
Is this added in `master` and published on nuget (latest 4.0.2)?
I couldn't seem to get Option.Headers from nuget 4.0.2. How do we utilise this ability to add headers to request?

**Pull request closed without merging**
