### PR TITLE
[WIP] Linq syntax based queries 

### PR DESCRIPTION
**Pull request by pikax**
Linq based queries, Inspiration from #93 

### Schema
```csharp
public class Schema
{
  public Person Person { get; set; }
  public Person Hero { get; set; }
}
```

### Expression
Allow to describe query from expression:
```csharp
Gql<Schema>.Query(x => new
{
  hero = new
  {
    x.Hero.Name
  }
});

// or

Gql<Schema>.Query(x => new
{
  hero = Gql.Field(x.Hero, h => new
  {
    h.Name
  })
});
```

builds to: 
```gql
{
  hero {
    name
  }
}
```
### Alias & Lists
it supports `alias` and lists:
```csharp
Gql<Schema>.Query(schema => new
{
  hero = new
  {
    schema.Hero.Name,

    friends = schema.Hero.Friends.Select(f => new
    {
      f.Name
    })
  }
});
```
builds to:
```gql
  {
    hero {
      name
      friends {
        name
      }
    }
  }
```

### Parameters

working with parameters: 
```csharp
Gql<Schema>.Query((schema, args) => new
{
  hero = Gql.Field(schema.Hero, h => new
  {
    h.Name
  }, new { args.first, offset = 10 })
}, new { first = default(int) })
```
Query builds to 
```gql
query ($first: Int!)   {
    hero (first: $first) {
      name
    }
  }
```

### return
```csharp
var expression = Gql<Schema>.Query(x => new
{
  hero = new
  {
    x.Hero.Name
  }
});

var request = expression.Build();
// after getting the response
expression.FromResponse(response).hero.Name; // typed response
expression.FromResponse(response).hero.Friends; // compile error Friends doesn't exist
```

### Requesting
```csharp
var expression = Gql<SwapiSchema>.Query((schema, args) => new
{
  person = Gql.Field(schema.Person, x => new
  {
    x.Name,
    FilmConnection = new
    {
      films = x.FilmConnection.Films.Select(f => new
      {
        f.Title
      })
    }
  }, new {args.personID }),

  allFilms = Gql.Field(schema.AllFilms, x => new
  {
    films = x.Films.Select(f => new
    {
      f.Title
    })
  })
}, new { personID = default(GqlID<int>) });


var response = await this.GraphQLClientSwapi.SendAsync(expression, new { personID = GqlID.From(1) });

Assert.Equal(4, response.Data.person.FilmConnection.films.Count());
```

This allows to have type checking if the types are being shared.

**NOTE** work in progress

### CODE REVIEW

**Comment by PascalSenn** [comment]
Uh. Interesting! 
Could work nicely together with https://github.com/dotansimha/graphql-code-generator

**Comment by pikax** [comment]
@PascalSenn yep, it also should work nicely if you have microservices on your solution and you want to apply renames across all the projects.

**Comment by PascalSenn** [comment]
Basically the use case we have
Do you generate the schema .net types?

**Comment by pikax** [comment]
atm my main use is for server-to-server, the types are in a project in the solution, it's being use for the graphql server and graphql client.

But you could generate your schema using some graphql code generator and use this to have type inference.

**Comment by gregsdennis** [comment]
@pikax you should publish this yourself.

**Comment by pikax** [comment]
@gregsdennis why do you say that?

**Comment by gregsdennis** [comment]
@pikax because it's good, and it doesn't seem like this lib is going to pick it up.  It's really just a GQL query builder.  You don't need to publish a full client.

For now, I've copied it to a personal project of mine.  I'm planning on filling it out a bit more.

**Comment by pikax** [comment]
@gregsdennis I thought it would be better integrated in the graphql-client since I started using this library when working with the graphql with dotnet.

I might release as a package in the future :)

**Comment by gregsdennis** [comment]
Yeah I had done the same with my PR.  Happily what you put together stands on its own as a query builder.

**Comment by rose-a** [comment]
@pikax would be awesome if you can find the time to get that ready for merging it into [develop](https://github.com/graphql-dotnet/graphql-client/tree/develop)

**Comment by pikax** [comment]
@rose-a I can fix the merge issues, but not sure when I will have time to follow this PR through.

I don't remember what was missing at the time

**Comment by vladop** [comment]
What happened to this? There are also few other really small libraries to do this query building. What is currently best way or best library to handle scenario of creating queries in type safe way?

**Comment by gregsdennis** [comment]
It was ignored.  I developed a mechanism that was specific to my personal project, but I haven't generalized it enough to publish it.

**Comment by pikax** [comment]
Yeah I moved on, currently not doing dotnet nor gql, so I don't really need this functionality anymore.

**Comment by vladop** [comment]
For anyone interested there is https://github.com/charlesdevandiere/graphql-query-builder-dotnet query builder which works good with this lib. (You just generate fully generated query string to Query property (and ignore Variables). I didn't tested some advanced scenarios, but basic query, subquery, passing variables works great

**Pull request closed without merging**
