### PR TITLE
Address #630

### PR DESCRIPTION
**Pull request by lol768**
See #630

### CODE REVIEW

**Comment by lol768** [comment]
This works when I publish the package locally, now, and reference it in a `net8.0` project:

image


It still continues to work in `netstandard2.0` projects, but the IDE understandably doesn't know what the stub attribute means/is.

**Comment by rose-a** [comment]
Hi, thanks for the contribution... please allow me some time for review, I'll hopefully manage to have a look at it within the next few days...

**Review by rose-a — CHANGES_REQUESTED** [review]
THe attribute should be added to the extension methods directly accepting a query string, too.

https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client.Abstractions/GraphQLClientExtensions.cs

**Review by rose-a — APPROVED** [review]

**Comment by lol768** [comment]
Thanks for reviewing @rose-a 🙂

**Pull request merged**
